apiVersion: apps/v1
kind: Deployment
metadata:
  name: vproapp
  label:
    app: vproapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vproapp
  template:
    metadata:
     labels:
       app: vproapp
    spec:
      containers:
      -  name: tomcat
         image: vprofile/vprofileapp
         ports:
         - name: vproapp-port
           containerPort: 8080
      
      initContainers:
      - name: init-mydb
        image: busybox
        command: ['sh', '-c', 'until nslookup dbdep.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for mydb; sleep 2; done;']  
      - name: init-mamcached
        image: busybox:latest
        command: ['sh' , '-c', 'until nslookup mcdep.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for mydb; sleep 2; done;']    
      
