services:
  vprodb:
    build:
      context: ./Dockerfiles/db
    image:
    ports:
      - "3306:3306"
    volumes:
      - vprodbdata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=vprodbpass