---
- name: Installation of packages
  hosts: webservers
  become: yes
  gather_facts: yes

  tasks:
    - name: install httpd
      yum:
        name: httpd
        state: present
    - name: start service
      service:
        name: httpd
        state: started
        enabled: yes
    - name: loops
      yum:
        name: "{{item}}"
        state: absent
      loop:
        - wget
        - unzip

- name: install on db server
  hosts: dbserver
  become: yes
  gather_facts: yes

  tasks:
    - name: install maria
      yum:
        name: mariadb-server
        state: present

    - name: start mariadb service
      service:
        name: mariadb
        state: started
        enabled: yes

